tools:
  maven: '3.6.0'
  jdk:
    name: 'Azul JDK 11'

parameters:
  - name: tag
    type: string
  - name: testrunid
    type: string
  - name: reportPath
    type: string

env:
  global:
    variables:
      reportUrl: "---URL---"
      buildUrl: "http://localhost:8080/job/APIAutomation/"
      REPOSITORY_URL: "https://github.com/Sumit10031995/APIFramework.git"
      appName: "QE_FRAMEWORK"
      DEFAULT_TAG: 'APITesting'
      testEnvironment: "${TestEnvironment}"
      buildLink: "${buildUrl}/${BUILD_NUMBER}"
      extentReportLink: "${reportUrl}/${JOB_NAME}/${BUILD_NUMBER}/${reportPath}"
      branchName: "${TRIGGER_BRANCH}"
      tagName: "${tag}"

triggers:
  push:
    branches:
      ignore:
        - '*'
  cron:
    - cron: '30 18 * * *'  # every day 7:30 AM IST

jobs:
  flows:
    default:
      - flow:
          name: 'multiFlows'

    APITesting:
      - script:
          name: 'Set APITesting tag'
          steps:
            - setPipelineVariable:
                name: tag
                value: 'APITesting'
            - flow:
                name: 'multiFlows'

    multiFlows:
      - script:
          name: 'Version of tools'
          steps:
            - shell: 'echo "Versions of tools.."'
            - shell: 'java -version'
            - shell: 'mvn -v'
      - script:
          name: 'Handle testrunid'
          steps:
            - if:
                condition: "${env.testrunid}"
                steps:
                  - shell: 'echo "Job Triggered with RUN ID ${env.testrunid}"'
                else:
                  - script:
                      name: 'Generate testrunid if not provided'
                      steps:
                        - setPipelineVariable:
                            name: testrunid
                            value: '${currentBuildTime("yyyy-MM-dd_HH-mm-ss-SSS")}'
                        - shell: 'echo "Job Triggered with RUN ID ${env.testrunid}"'
            - script:
                name: 'Handle tag'
                steps:
                  - if:
                      condition: "${env.tag}"
                      steps:
                        - shell: 'echo "Job Triggered with Tag ${env.tag}"'
                        - setPipelineVariable:
                            name: reportPath
                            value: "testResult/Test_Results_${env.tag}.html"
                      else:
                        - setPipelineVariable:
                            name: tag
                            value: "${DEFAULT_TAG}"
                        - shell: 'echo "Job Triggered with Default Tag ${env.tag}"'
                        - setPipelineVariable:
                            name: reportPath
                            value: "testResult/Test_Results_${env.tag}.html"
      - script:
          name: 'Run Maven commands'
          steps:
            - shell: 'mvn clean'
            - shell: 'mvn -f ./pom.xml test -Dislocalrun="false" -Dsurefire.suiteXmlFiles="./${env.tag}.xml" -DrunId=${env.testrunid}'
      - flow:
          name: 'publishReport'
