pipeline:
  agent:
    any

  environment:
    JAVA_HOME: "/path/to/your/jdk"

  parameters:
    - name: tag
      type: string
      default: 'APITesting'
    - name: testrunid
      type: string
      default: "${currentBuildTime('yyyy-MM-dd_HH-mm-ss-SSS')}"
    - name: reportPath
      type: string
      default: "testResult/Test_Results_${tag}.html"

  options:
    skipDefaultCheckout: true  # Disable default checkout to handle it explicitly

  stages:
    - stage: Checkout
      steps:
        - checkout scm

    - stage: Build
      steps:
        - script:
            name: 'Build with Maven'
            script: |
              mvn clean
              mvn -f ./pom.xml package

    - stage: Test
      when: expression { params.testrunid != '' }
      steps:
        - script:
            name: 'Run Tests'
            script: |
              mvn -f ./pom.xml test \
                -Dislocalrun="false" \
                -Dsurefire.suiteXmlFiles="./${params.tag}.xml" \
                -DrunId=${params.testrunid}

    - stage: Publish Reports
      steps:
        - script:
            name: 'Publishing reports...'
            script: |
              echo "Report URL: ${env.reportUrl}/${env.JOB_NAME}/${env.BUILD_NUMBER}/${params.reportPath}"
              # Add additional steps to publish reports or artifacts as needed

    - stage: Cleanup
      steps:
        - deleteDir()

  post:
    always:
      - script:
          name: 'Completion Message'
          script: |
            echo "Build completed successfully!"

    failure:
      - script:
          name: 'Failure Message'
          script: |
            echo "Build failed! Check logs for details."

triggers:
  cron:
    - cron: '30 18 * * *'  # Run every day at 7:30 AM IST
